#!/bin/sh

# ------------------------------------------------------------------------------
#  Set Chrome as the default browser
# ------------------------------------------------------------------------------
osascript ~/kod/personal/dotfiles/common/chrome/set-default-browser.scpt chrome
