#!/bin/sh

echo "Installing brew and git which is required for Rotz"

# ask for sudo access at start
sudo -v

# ------------------------------------------------------------------------------
#  Install Brew and its dependencies.
# ------------------------------------------------------------------------------

if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/mesut/.zprofile

zsh

brew update
brew upgrade
# chmod needed for brew completion
chmod -R go-w "$(brew --prefix)/share"


# ------------------------------------------------------------------------------
#  Install Rotz github.com/volllly/rotz
# ------------------------------------------------------------------------------
brew install volllly/tap/rotz

# ------------------------------------------------------------------------------
#  Clone the repository to ~/kod/personal/dotfiles
# ------------------------------------------------------------------------------

DOTFILES_PATH=~/kod/personal/dotfiles

git clone https://github.com/koca/dotfiles.git $DOTFILES_PATH
cp $DOTFILES_PATH/rotz-config.yaml /Users/mesut/Library/Application\ Support/com.rotz/config.yaml

echo "---------------------------------------------"
echo " Dotfiles successfully cloned to $DOTFILES_PATH"
echo "---------------------------------------------"
echo ""
echo "Next steps:"
echo "1. Navigate to the dotfiles directory:"
echo "   cd ~/kod/personal/dotfiles"
echo ""
echo "2. Execute the installation command suitable for your operating system:"
echo "   - MacOS: rotz link macos/brew && rotz install"
echo "   - Linux: rotz install"
echo "   - Windows: rotz install"
echo ""
echo "For more information, refer to the README.md file."
echo "---------------------------------------------"
